theme: jekyll-theme-minimal
title: the Gaussian Process web site
description: This web site aims to provide an overview of resources concerned with probabilistic modeling, inference and learning based on Gaussian processes.
